enabledArenas: []

defaultLanguage: en
timerResetOnJoin: false
bypassCommands:
- msg
- ban
- kick
- mute
- a
webPlayer:
  enabled: false
  mysql:
    host: localhost
    port: 3306
    database: WebPlayer
    user: root
    password: ''