name : BlockParty
version : 0.4
authors: [Leon167, XxChxppellxX]
description: Official BlockParty plugin
website: http://www.Cloud-Mine.de
main: com.lekohd.blockparty.Main

depend:
  - WorldEdit
softdepend:
  - BarAPI
  - NoteBlockAPI

commands:
  blockparty:
    aliases: [bp,block,blockp]
