name : BlockParty
version : 0.9.3
authors: [Leon167, XxChxppellxX, ScriptJunkie, CPx1989]
description: Official BlockParty Plugin!
website: http://www.Cloud-Mine.de
main: com.lekohd.blockparty.BlockParty

depend:
  - WorldEdit
softdepend:
  - BarAPI
  - NoteBlockAPI
  - VanishNoPacket

commands:
  blockparty:
    aliases: [bp,block,blockp,bparty]
